version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

jobs:
  build:
    working_directory: ~/pleiepenger-dokument
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew check shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - nais/docker-deploy:
          image: navikt/pleiepenger-dokument
  check:
    working_directory: ~/pleiepenger-dokument
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}

workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - build:
          context: NAIS deployment
          filters:
            branches:
              only:
                - master
                - /dev-.*/
      - check:
          filters:
            branches:
              ignore:
                - master
                - /dev-.*/
      - nais/deploy:
          name: dev-sbs-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/dev-sbs.yml
          environment: dev-sbs
          team: dusseldorf
          filters:
            branches:
              only:
                - master
                - /dev-.*/
          requires:
            - build
      - nais/deploy:
          name: dev-fss-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/dev-fss.yml
          environment: dev-fss
          team: dusseldorf
          filters:
            branches:
              only:
                - master
                - /dev-.*/
          requires:
            - build