version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.4.1'

jobs:
  build:
    working_directory: ~/pleiepenger-dokument
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew shadowJar
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - nais/docker-deploy:
          image: navikt/pleiepenger-dokument

  check:
    machine: true
    working_directory: ~/pleiepenger-dokument
    steps:
      - restore_cache:
          keys:
            - openjdk-11
      - run:
          name: install openjdk-11
          command: |
            set -e
            mkdir -p ~/.apt-cache
            sudo rm -rf /var/cache/apt/archives
            sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial
            sudo add-apt-repository ppa:openjdk-r/ppa
            sudo apt update -q
            sudo apt install -qy openjdk-11-jdk
            sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      - save_cache:
          paths:
            - ~/.apt-cache
          key: openjdk-11
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}

workflows:
  version: 2
  deploy-docker-and-nais:
    jobs:
      - check
      - build:
          context: NAIS deployment
          requires:
            - check
          filters:
            branches:
              only:
                - master
                - /dev-.*/
      - nais/deploy:
          name: dev-sbs-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/dev-sbs.yml
          environment: dev-sbs
          team: dusseldorf
          filters:
            branches:
              only:
                - master
                - /dev-.*/
          requires:
            - build
      - nais/deploy:
          name: dev-fss-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/dev-fss.yml
          environment: dev-fss
          team: dusseldorf
          filters:
            branches:
              only:
                - master
                - /dev-.*/
          requires:
            - build
      - nais/deploy:
          name: prod-sbs-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/prod-sbs.yml
          environment: prod-sbs
          team: dusseldorf
          filters:
            branches:
              only:
                - master
          requires:
            - build
      - nais/deploy:
          name: prod-fss-deploy
          build-and-push-docker-image: false
          repo: navikt/pleiepenger-dokument
          image: navikt/pleiepenger-dokument
          github-app-id: 35124
          nais-template: nais/prod-fss.yml
          environment: prod-fss
          team: dusseldorf
          filters:
            branches:
              only:
                - master
          requires:
            - build