apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: k9-dokument
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{ image }}:{{ tag }}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://k9-dokument.nais.oera-q.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: LOGIN_SERVICE_V1_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/NAVtestB2C.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
    - name: S3_SERVICE_ENDPOINT
      value: https://objectstore.nais.oera-q.local
    - name: S3_SIGNING_REGION
      value: us-east-1
    - name: S3_EXPIRATION_IN_DAYS
      value: "1"
    - name: VIRUS_SCAN_URL
      value: http://clamav.nais.svc.nais.local/scan
    - name: BASE_URL
      value: https://k9-dokument.nais.oera-q.local